name: Android CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest  # 更稳定的 LTS 版本
    # ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Java 环境
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3.  Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      # 4. 验证 Gradle Wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      # 5. 构建 APK
      - name: Build APK
        run: ./gradlew app:assembleRelease

      # 6. 上传 APK (更新到 v4)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: metro-release-apk
          path: app/build/outputs/apk/release/*.apk

